import type { MapPoint } from "../types";
import type { MapPoint } from "../types";
import { asset } from "../../assets";

export const perimeterPoints: MapPoint[] = [
  {
    id: "north-relay",
    label: "North Relay",
    subtitle: "Upper relay structure",
    description: "Northern relay structure overlooking the upper sector.",
    notableLoots: ["scrap-metal", "medkit", "scanner"],
    image: "/maps/perimeter/zones/north-relay.jpg",
    x: 46,
    y: 31,
    kind: "area",
    category: "location",
  },
  {
    id: "station",
    label: "Station",
    subtitle: "Transit-linked facility",
    description: "Eastern structure connected to the transit axis.",
    notableLoots: ["military-rifle", "rifle-ammo", "weapon-mod"],
    image: "/maps/perimeter/zones/station.jpg",
    x: 73,
    y: 37,
    kind: "area",
    category: "location",
  },
  {
    id: "hauler",
    label: "Hauler",
    subtitle: "Transport hub",
    description: "Western transport point linked to the central route.",
    notableLoots: ["scrap-metal", "energy-shield", "unknown-component"],
    image: "/maps/perimeter/zones/hauler.jpg",
    x: 30,
    y: 48,
    kind: "area",
    category: "location",
  },
  {
    id: "data-wall",
    label: "Data Wall",
    subtitle: "Central corridor",
    description: "Central corridor crossing the zone from west to east.",
    notableLoots: ["artifact-core", "scanner", "weapon-schema"],
    image: "/maps/perimeter/zones/data-wall.jpg",
    x: 49,
    y: 48,
    kind: "area",
    category: "location",
  },
  {
    id: "tunnels",
    label: "Tunnels",
    subtitle: "Underground network",
    description: "Interior passage network in the central-east sector.",
    notableLoots: ["medkit", "unknown-component", "encrypted-keycard"],
    image: "/maps/perimeter/zones/tunnels.jpg",
    x: 61,
    y: 56,
    kind: "area",
    category: "location",
  },
  {
    id: "east-wall",
    label: "East Wall",
    subtitle: "Outer boundary",
    description: "Eastern boundary and continuation toward the southeast.",
    notableLoots: ["rifle-ammo", "frag-grenade", "scanner"],
    image: "/maps/perimeter/zones/east-wall.jpg",
    x: 75,
    y: 59,
    kind: "area",
    category: "location",
  },
  {
    id: "ravine",
    label: "Ravine",
    subtitle: "Broken terrain",
    description: "Broken terrain cutting through the center-south.",
    notableLoots: ["ancient-relic", "medkit", "black-market-chip"],
    image: "/maps/perimeter/zones/ravine.jpg",
    x: 52,
    y: 67,
    kind: "area",
    category: "location",
  },
  {
    id: "overflow",
    label: "Overflow",
    subtitle: "Industrial basin",
    description: "Lower-west basin and industrial spill sector.",
    notableLoots: ["scrap-metal", "unknown-component", "energy-shield"],
    image: "/maps/perimeter/zones/overflow.jpg",
    x: 39,
    y: 84,
    kind: "area",
    category: "location",
  },
  {
    id: "columns",
    label: "Columns",
    subtitle: "Structural remains",
    description: "Lower-central area marked by structural remains.",
    notableLoots: ["ancient-relic", "artifact-core", "weapon-mod"],
    image: "/maps/perimeter/zones/columns.jpg",
    x: 55,
    y: 86,
    kind: "area",
    category: "location",
  },
  {
    id: "south-relay",
    label: "South Relay",
    subtitle: "Relay complex",
    description: "Southern relay complex dominating the lower-right sector.",
    notableLoots: ["artifact-core", "priority-disk", "encrypted-keycard"],
    image: "/maps/perimeter/zones/south-relay.jpg",
    x: 69,
    y: 78,
    kind: "area",
    category: "location",
  },

  /* =========================
     CREW EXFIL
  ========================= */

  {
    id: "north-relay-exfil1",
    label: "North Relay's Exfil N'1",
    subtitle: "Northern extraction route",
    description: "Primary extraction route positioned near North Relay.",
    image: "/maps/perimeter/zones/north-relay-exfil1.jpg",
    x: 35,
    y: 22,
    kind: "exfil",
    category: "location",
  },
  {
    id: "north-relay-exfil2",
    label: "North Relay's Exfil N'2",
    subtitle: "Northern extraction route",
    description: "Secundary extraction route positioned near North Relay.",
    image: "/maps/perimeter/zones/north-relay-exfil2.jpg",
    x: 35,
    y: 25,
    kind: "exfil",
    category: "location",
  },

  {
    id: "station-exfil",
    label: "Station's Exfil",
    subtitle: "Eastern extraction route",
    description: "Extraction point accessible from Station sector.",
    image: "/maps/perimeter/zones/station-exfil.jpg",
    x: 71,
    y: 40,
    kind: "exfil",
    category: "location",
  },

  {
    id: "hauler-exfil",
    label: "Hauler's Exfil",
    subtitle: "Western extraction route",
    description: "Extraction route located near Hauler facilities.",
    image: "/maps/perimeter/zones/hauler-exfil.jpg",
    x: 20,
    y: 50,
    kind: "exfil",
    category: "location",
  },

  {
    id: "overflow-exfil",
    label: "Overflow's Exfil",
    subtitle: "Southern-west extraction",
    description: "Remote extraction route available near Overflow.",
    image: "/maps/perimeter/zones/overflow-exfil.jpg",
    x: 26,
    y: 80,
    kind: "exfil",
    category: "location",
  },

  {
    id: "south-relay-exfil",
    label: "South Relay Exfil",
    subtitle: "Southern extraction route",
    description: "Extraction route available from South Relay sector.",
    image: "/maps/perimeter/zones/south-relay-exfil.jpg",
    x: 60,
    y: 63,
    kind: "exfil",
    category: "location",
  },
];